server:
  port: 0


spring:

  application:
    name: account-service

  config:
    import: optional:configserver:http://localhost:8888


  data:
    mongodb:
      uri: mongodb://localhost:27017/account-db



eureka:

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


  instance:
    prefer-ip-address: true