package com.banking.accountservice.service;

import com.banking.accountservice.dto.TransactionDTO;
import com.banking.accountservice.model.Account;
import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.core.Observable;
import io.reactivex.rxjava3.core.Single;

import java.util.List;


/**
 * Service interface that defines account management operations.
 *
 * This interface provides reactive methods for creating, retrieving,
 * updating, deleting accounts, calculating transaction commissions,
 * and managing account information through Redis cache.
 *
 * RxJava 3 reactive types are used to support asynchronous and
 * non-blocking operations.
 */
public interface AccountService {
    /**
     * Creates a new account.
     *
     * @param account account information to be registered
     * @return created account wrapped in a reactive Single response
     */
    Single<Account> create(Account account);
    /**
     * Retrieves all accounts registered in the system.
     *
     * @return list of accounts wrapped in a reactive Single response
     */
    Single<List<Account>> findAll();
    /**
     * Retrieves an account by its identifier.
     *
     * @param id account identifier
     * @return account information wrapped in a reactive Single response
     */
    Single<Account> findById(String id);
    /**
     * Updates an existing account.
     *
     * @param id account identifier to update
     * @param account account information with updated values
     * @return updated account wrapped in a reactive Single response
     */
    Single<Account> update(String id, Account account);
    /**
     * Deletes an account by identifier.
     *
     * @param id account identifier to delete
     * @return completion signal using reactive Completable
     */
    Completable delete(String id);
    /**
     * Calculates the commission generated by account transactions.
     *
     * The commission is calculated based on the number of transactions
     * that exceed the allowed free transaction limit.
     *
     * @param accountId account identifier
     * @param txs list of transactions used for commission calculation
     * @return calculated commission value
     */
    double calculateCommission(String accountId, List<TransactionDTO> txs);
    /**
     * Retrieves accounts stored in Redis cache.
     *
     * @return cached accounts list wrapped in a reactive Single response
     */
    Single<List<Account>> findAllFromRedis();

    /**
     * Stores account information in Redis cache.
     *
     * @param accounts list of accounts to be stored
     * @return operation result wrapped in a reactive Single response
     */
    Single<Boolean> saveAllToRedis(List<Account> accounts);
}